##' show method for \code{EnrichResult} instance
##'
##' @title show method
##' @rdname show-methods
##' @param object A \code{EnrichResult} instance.
##' @importFrom methods show
##' @author Haixiu Yang
##' @return print info
##' @export
##' @examples
##' demo.data <- c(1636, 351, 102)
##' res <- doEnrich(interestGenes = demo.data, traditional = TRUE)
##' show(res)
setMethod("show", "EnrichResult", function(object) {
  message("----------------------- EnrichResult object -----------------------\n")
  message("Method of enrichment:")
  if (object@traditional == TRUE) {
    message("\t classic ORA")
  } else if (object@penalize == TRUE) {
    message("\t Global Weighted Model")
  } else {
    message("\t Weighted Model")
  }
  message("\t '", object@test, "' Statistical model with the '", object@method, "' Multiple hypothesis correction")

  message("Enrichment cutoff layer: ", object@m)
  message("interestGenes number: ", length(object@interestGenes))

  filt_res <- dplyr::filter(object@enrich, cg.len != 0, gene.len >= object@minGsize, gene.len <= object@maxGsize)
  DOIDcount <- length(filt_res$DOID)
  sig_DOID <- length(dplyr::filter(object@enrich, p < object@delta)$DOID)

  message(DOIDcount, " DOTerms scored: ", sig_DOID, " terms with p < ", object@delta)

  message("Parameter setting:")
  message("\t Enrichment cutoff layer: ", object@m)
  message("\t Doterm gene number limit: minGsize ", object@minGsize, ", maxGsize ", object@maxGsize)
  message("\t Enrichment threshold: ", object@delta)
})

##' viewDetailResult method for \code{EnrichResult} instance
##'
##' @title viewDetailResult method
##' @name viewDetailResult
##' @rdname viewDetailResult
##' @param object A \code{EnrichResult} instance.
##' @param ... Additional arguments.
##' @author Haixiu Yang
##' @return data.frame of complete enrichment results
##' @examples
##' # Assuming 'weighted_demo_result' is an EnrichResult object generated by doEnrich()
##' demo.data <- c(1636, 351, 102, 2932, 3077)
##' weighted_demo_result <- doEnrich(interestGenes=demo.data,
##'                         test="fisherTest",
##'                         method="holm",
##'                         m=1,
##'                         minGsize=10,
##'                         maxGsize=2000,
##'                         delta=0.05,
##'                         penalize=TRUE)
##' detail_df <- viewDetailResult(weighted_demo_result)
##' head(detail_df)
##' @export
setGeneric("viewDetailResult", function(object, ...) standardGeneric("viewDetailResult"))

##' @rdname viewDetailResult
##' @export
setMethod("viewDetailResult", "EnrichResult", function(object) {
  return(object@enrich)
})

##' viewSummaryResult method for \code{EnrichResult} instance
##'
##' @title viewSummaryResult method
##' @name viewSummaryResult
##' @rdname viewSummaryResult
##' @param object A \code{EnrichResult} instance.
##' @param P pvalue cutoff.
##' @param Q p.adjust cutoff.
##' @param ... Additional arguments.
##' @author Haixiu Yang
##' @return data.frame of standardized enrichment results
##' @examples
##' # Assuming 'weighted_demo_result' is an EnrichResult object generated by doEnrich()
##' demo.data <- c(1636, 351, 102, 2932, 3077)
##' weighted_demo_result <- doEnrich(interestGenes=demo.data,
##'                         test="fisherTest",
##'                         method="holm",
##'                         m=1,
##'                         minGsize=10,
##'                         maxGsize=2000,
##'                         delta=0.05,
##'                         penalize=TRUE)
##' summary_df <- viewSummaryResult(weighted_demo_result)
##' head(summary_df)
##' @export
setGeneric("viewSummaryResult", function(object, P = 1, Q = 1, ...) standardGeneric("viewSummaryResult"))

##' @rdname viewSummaryResult
##' @export
setMethod("viewSummaryResult", "EnrichResult", function(object, P = 1, Q = 1) {
  res <- object@enrich
  res <- res[res$p <= P & res$p.adjust <= Q, ]
  res <- res[order(res$p), ]

  # 直接从内部环境调用 sysdata.rda 中的 dotermgenes 长度，摒弃不安全的硬编码
  bg_len <- length(dotermgenes)

  core_df <- data.frame(
    DOID = res$DOID,
    DOTerm = res$DOTerm,
    p = res$p,
    p.adjust = res$p.adjust,
    geneRatio = paste0(res$cg.len, "/", res$ig.len),
    bgRatio = paste0(res$gene.len, "/", bg_len),
    cg = vapply(res$cg.arr, function(x) {
      paste0(x, collapse = "/")
    }, character(1)),
    stringsAsFactors = FALSE
  )

  return(core_df)
})
